text3 = """<p>Wall Street had to pay top dollar to compensate for the mental and physical stress and constant pressure, and retaining good people was difficult because other firms were always hiring talent and headhunters circled like sharks. Most everybody working on Wall Street regardless of role or level had scarce industry skills which gave them strong cards to play for hiring, promotion, and advancement. I saw recruiters do a lot of devious and borderline illegal stuff trying to poach talent.</p>

<p>Wall Street innovations I was part of like new electronic markets made investing cheaper and more accessible for everyone and eliminated most trading commissions for the first time. Digital trading systems and exchanges were spurred on by new regulations that collectively made institutional trading and investing easier and cheaper. Markets where trades were executed became more liquid, more anonymous, better prices, and lower trading costs that benefitted both retail and institutional investors.</p>

<p>Wall Street money sponsored charitable events that raised millions for worthy causes, characterized by donors as “giving back” for their good fortune. But it often seemed the charitable cause was secondary to rich and successful people partying. I went to dozens of “charity galas” and award ceremonies “honoring” whoever had donated the most money to the cause that year. It cost me thousands of dollars for a table but I used it for business. Charities were another beneficiary of the broader Wall Street and capital markets ecosystem of money and wealth.</p>

<p>Career success wasn’t meant to be equal but earned through measurable performance excellence. Performing in bands helped me develop the skills and confidence to interact with senior executives and traders at a young age. I learned how to develop business relationships in ways my competitors couldn’t match to cool and exclusive restaurants and nightlife in New York, Chicago, London, Tokyo, Sydney, Shanghai, Seoul, and Hong Kong. A great dinner and drinks were a given, but for many of my clients the night was just beginning after dinner.</p>
 
<p>I took clients to hot restaurants, clubs, and bars few even knew about and fewer could get into on their own, all part of client entertainment in the Wall Street fast lane. I took them to Broadway shows, museum openings, and private suites at concerts and sporting events. I played any cards I had and played all out to win deals, but I played by the rules without stepping over admittedly gray lines. During the '80s and '90s there were few if any hard lines except overt bribes and money changing hands, and as rules and policies changed over time I changed too but everybody had less fun.</p>

<p>Today’s highly restrictive rules for business entertainment contribute to inferior business outcomes, sacrificing the strategic alignment and new ideas that came from more relaxed out-of-office dialogue. Going out after work with clients made business more productive, and we had fun but I never saw any corruption anywhere. Now extreme restrictions on permissible client entertainment and cost caps can make going to Chick-fil-A and getting a Cookies & Cream milkshake look like a decent option.</p>
 
<p>I pioneered different product, data, and service innovations in ways few others ever get to do even once, sometimes pursuing my own ideas and sometimes making the ideas of others real. Selling to Wall Street meant winning the cost-benefit debate in a risk/reward culture where ROI could be realized in a single lucrative trade or by avoiding a big risk or mistake. Having a trading background made it easy for me to identify business inefficiencies and problems in financial services, and it wasn’t too hard to learn enough about advanced IT to understand what was technically and functionally possible. My knowledge convergence of capital markets and IT led to impactful and innovative new product and services kept changing the market.</p>

<p>After the digital transformation of Wall Street beginning with Triarch the marginally controlled trading floor chaos I loved was replaced by computers, networks, datafeeds, and real-time algorithms and applications running in an equipment room. There were many fewer traders, shrinking trading floors, and legacy exchanges were fighting for survival against new market entrants introducing new trading methods.</p>

<p>Now the action was in the flashing lights and perpetual hum of high-speed computers and specialized cooling systems in high-tech equipment rooms. Computers were faster, mostly smarter, could analyze infinitely more prices and markets simultaneously, and made fewer mistakes than human traders. The computers also didn't drink or do drugs, complain, screw the employees, succumb to stress requiring pharmaceuticals or therapy, or get paid millions in salary and bonus only to still want more.</p>\n"""
