text3 = """<p>I think today's highly restrictive rules for client socialization lead to inferior business outcomes, missing the strategic alignment and new ideas that often come from more relaxed out-of-office dialogue. Socializing with others fostered closer internal and external relationships that made business more productive and fun. Now extreme restrictions on permissible client entertainment and cost caps can make going to Chick-fil-A for a Cookies & Cream milkshake look like a decent option.</p>
<p>I pioneered numerous product, data, and service innovations, most with my own ideas and sometimes making the ideas of others real. Selling on Wall Street meant winning tough cost-benefit debates in a smart, demanding risk/reward culture. Cost was less important than tangible innovation driving competitive differentiation since ROI could be realized in a single lucrative trade or by avoiding a big downside risk.</p>
<p>I used my trading experience to identity business inefficiencies and challenges in financial services, and I studied cutting-edge IT advances to know what was technically and functionally possible to address them. My deep industry and IT knowledge coupled with a good bit of creativity, critical thinking, and problem solving led to impactful new product and service ideas that kept changing the market.</p>
<p>After the digital transformation of Wall Street trading systems that began with Triarch the marginally controlled chaos I loved on the trading floor was replaced by computers, networks, datafeeds, and real-time algorithms and applications running in equipment rooms. There were far fewer traders, shrinking trading floors, and legacy exchanges were fighting for survival against new market entrants introducing faster, cheaper, and more transparent trading methods and market structures.</p>
<p>Now the real action was in the flashing lights and perpetual hum of high-speed computers and specialized cooling systems in high-tech equipment rooms. Computers were faster, mostly smarter, could analyze infinitely more prices and markets simultaneously, and made fewer mistakes than human traders. The computers also didn't drink or do drugs, complain, screw the employees, succumb to stress requiring pharmaceuticals or therapy, or get paid millions in salary and bonus only to still want more.</p>
<p>Wall Street and global capital markets operated at a pace and with pressures few people could conceive of or endure, but some people like me thrived in the adrenaline-fueled lifestyle if you avoided too many crutches. Weed and alcohol had long been part of the Wall Street scene, but the surge of cocaine usage in the 1980s was different and ruined lives. The financial and personal rewards of working on Wall Street were diverse and many, but they came at a cost. I was lucky the era finally ended because the constant travel, stress and pressure, and too many late nights out only to do it again the next day were taking a physical and mental toll on me too.</p>
<p>By the mid-1990s Wall Street life was settling down somewhat and regulatory changes spurred a new cycle of innovation. New alternatives to traditional exchanges like crossing and matching systems and investment bank "dark pools" that internalized customer trades with the bank's own trades proliferated. The alternative markets were faster, operated longer hours, and provided better prices, greater anonymity, and more transparent liquidity so sophisticated algorithms could outthink and outmaneuver human traders. Better trade execution was particularly impactful on large trades like those of big institutional investors and funds.</p>
<p>High-frequency and algorithmic trading expanded from stocks into bonds, derivatives, commodities, and foreign exchange. Most trades were now executed by "smart algorithms" accessing and comparing fast, liquid electronic markets to get "best execution" that was measured and reported on. Budgets were effectively unlimited for high-frequency arbitrage traders and market makers to win the speed race, where milliseconds of speed advantage in data delivery meant market insights and low risk trading profits. Highly specialized hardware, software, data, networking, and services vendors sold financial institutions the means to compete and win in the markets. Everybody profited including me.</p>
<p>The stately marble environs of the NYSE and the amphitheater "trading pits" of the Chicago commodity and options exchanges became expensive liabilities. They were very expensive to maintain and enhance but no longer served any real purpose. Exchange trading floors were good TV sets for shows like CNBC's Squawk on the Street where I did interviews, but nothing significant happened on them any longer after trading and market making became electronic and automated.</p>
<p>Maintaining the physical trading space diverted management attention and investments needed for innovation and growth, and new alternative exchanges took more and more market share from traditional exchanges. The innovators made acquisitions, expanded into new geographies, traded more asset classes electronically for more hours, and prospered. Legacy exchanges that didn't adapt either faded into oblivion or were acquired by the winners.</p>
"""
