text4 = """<p>My former client NYSE was ultimately acquired by the Intercontinental Exchange (ICE), one of my new startup clients that our project team brought into existence. NYSE leadership dismissed my warnings about competitive threats for too long, too slow transforming their IT infrastructure and never developing an effective growth strategy. NYSE stayed a private members-only club for too long while the members became dinosaurs. Public exchanges and especially European exchanges were using investment capital and the markets to make acquisitions and to fund global expansion and strategic alliances.</p>
<p>As the '90s came to a close I had a front row seat to the separation of Andersen Consulting (AC) from Arthur Andersen (AA) and the global re-branding as Accenture preceding the blockbuster IPO. I'll share the inside story of how AC won the right to separate from AA and some previously untold stories of intrigue and political maneuvering along the way. Billions of dollars were at stake, and the way we prevailed in arbitration and then executed a global re-branding and an IPO in little more than a year will stay on business school curriculums for many years.</p>
<p>It was one of the fastest, most complex, and highest value global business transformations ever undertaken, and the Accenture IPO was only 2 months before the 9/11 terrorist attacks. You'll hear about the Andersen Worldwide global partners meeting in Paris where our future was decided and inside AC strategies to win in the International Chamber of Commerce arbitration. I was the long-time global client partner for our lead investment banker Goldman Sachs, and I represented capital markets as the industry managing partner on the roadshow marketing Accenture IPO shares to big institutional investors.</p>
<p>I was in New York City on 9/11 and survived through a highly improbable twist of fate. It involved a scheduled and then postponed London trip and an unplanned stop at my office that morning before going to the big market data conference I was sponsoring at Windows on the World. I survived while well over a hundred of my colleagues, clients, and friends at the conference and working in the towers didn't. Windows on the World was on the 106 th floor of One World Trade Center, and nobody escaped from up there. They were all victims of senseless Islamic ideological extremism by terrorists willing to kill people just going to work who were clueless about their bullshit cause or grievance.</p>
<p>In the weeks after 9/11 Accenture helped clients and the city of New York recover, even as we dealt with our own personal and professional losses. The region's telecommunications and network infrastructure in lower Manhattan was destroyed, and the global financial industry would break down without those links between New York and the rest of the world reestablished.</p>
<p>Nothing was ever the same after 9/11, from flying to just getting through building security to meet with clients. Even now I still can't forget seeing Muslims in many countries dancing in the streets celebrating 9/11 and the death of so many of my friends and colleagues and how close I came to dying myself with a wife and one year old son. The events of 9/11 prompted me to leave New York and move to South Carolina in 2003, but I still flew to NY or somewhere in the world every week for another 15 years.</p>
<p>After resigning as the Accenture capital markets global managing partner in December, 2007 I did independent consulting, designed and taught capital markets training seminars, and served on boards for a few years before joining KPMG in 2012 and leading Intelligent Automation. It was a chance to explore new ideas for using software process automation and AI to create new managed services and take operational efficiency and quality improvements beyond the limitations of global outsourcing. But after going back to work I found business life and norms had changed, and not for the better.</p>
<p>The preference-free meritocracy of Andersen Consulting and Accenture had given way to institutionalized special preferences and "diversity goals." Goals became de facto mandates and code words for de facto quotas in hiring, promotions, and compensation. I didn't like it nor did high performers who lost out to preferred identity group members with inferior qualifications and performance metrics. Who could blame them?</p>
<p>Business outcomes suffered, and most top leadership was too isolated from rank-and-file employees to see the widespread dissatisfaction with the erosion of meritocracy. They were ensconced in top floor offices, mistakenly believing that HR corporate platitudes promoting diversity and special considerations for preferred identity groups were welcomed by employees. Frequent promotions of lesser qualified and sometimes clearly unqualified individuals into higher roles elicited lots of internal chatter, and large numbers of high performers not in a preferred identity group resigned. Senior managers lost faith that superior performance would earn them admission into the partnership.</p>
<p>Working on Wall Street in the '80s and '90s was an amazing experience that established the foundation for my entire career. It was life in the fast lane personally and professionally, but it was also an unprecedented period of innovation, market disruption, and digital transformation of trading, capital markets, exchanges, and professional services. Later in my career I leveraged my Wall Street experience in real-time data, systems, applications, and algorithms to lead Intelligent Automation across industries. We designed and sold cutting-edge AI-enabled process automation solutions long before public awareness of AI grew after the launch of ChatGPT. Here's my story…</p>
"""
