text2 = """<p>Paper trade tickets were written by hand to be manually entered into a trade processing system off the trading floor. As I learned more about technology I realized that wouldn’t last on Wall Street. I thought about how trading would change until I had a chance to change it myself as an entrepreneur. High-speed computers, real-time data and networks, software and algorithms, and new alternative electronic markets were all enablers and results of the transformation.</p>

<p>For a career I moved from trading to designing and selling trading technology and services before traders were made obsolete by algorithms and software applications. I repurposed my trading experience to develop game-changing innovations in real-time trading systems, datafeeds, applications, and professional services that turned the art of the possible into cost-effective reality. Digital disruption and the proliferation of new electronic markets spread worldwide, transforming 200 years of financial market history and rendering large trading floors unnecessary.</p>

<p>Two of my companies designed and built the trading and market data distribution systems that changed Wall Street to make it more automated and real-time. Previously stereotyped and neglected mathematicians and software engineers became highly compensated “quants", “data scientists", and new members of the cool crowd. They used highly advanced mathematics along with real-time and historical data to develop trading strategies they turned into applications and algorithms run by ultra high-speed computers and networks.</p>

<p>A close partnership formed between Wall Street that was pursuing the last microsecond of speed advantage and the computer and networking companies leading the global performance race. Wall Street embraced any innovation that could create competitive advantages, implementing and often investing in the companies creating those innovations. My companies integrated the very best hardware, software, data, and networks into trading and data distribution systems we installed on trading floors worldwide. In a few more years I was selling long-term contracts to run and continuously improve them.</p>

<p>By the 1990s every high-performance IT vendor had dedicated sales teams focused on Wall Street and financial services. They wanted the revenue but also the drug-like high from winning on Wall Street which they leveraged in national and international marketing campaigns. In those days real drugs could also play a role in how those Wall Street sales were won given pervasiveness in the financial industry. It was all part of the game in the '80s and '90s, and I used the hardware and software vendors to further my own objectives.</p>

<p>I developed close relationships with senior trading and IT executives on Wall Street and in Silicon Valley, and they helped me especially at my smaller entrepreneurial companies. They helped me get to decision makers I didn’t know when I was pursuing a big sale, and I reciprocated with great dinners, shows, concerts, and the hottest clubs and bars they could handle. I became more visible in the media than anyone working in the capital markets, and TV and print interviews helped my credibility with clients and important strategic partners.</p>

<p>Wall Street digital innovations and real-time data eventually spread to other industries as the enabling technologies matured and prices decreased. Vivek Ranadive, one of my early trading system competitors, went on to evangelize the “real-time enterprise” and promoting “the power of now” after founding TIBCO. Later in my career I also moved beyond financial services to introduce AI-enabled software process automation across industries, but origins all traced back to the real-time data and algorithms during the digital disruption of Wall Street.</p>

<p>For me the trading floor was always an adrenaline rush dating to my first exposure as a recent college graduate. I wouldn’t have lasted long as an office worker, but I thought seriously about music full time. I began playing professionally when I was 15 and made enough money to help pay for my Duke University tuition when my family couldn’t have afforded it otherwise. I was still considering a performing and recording career at Duke but my demo record was stagnating disco was becoming the hot new genre and I had moved to rock after starting in jazz. So after graduating I accepted a management trainee job at a big bank, but I wasn’t happy there and rethinking everything until I discovered trading.</p>\n"""
