text4 = """<p>Wall Street and global capital markets operated at a pace and with pressures few people could conceive of or endure, but some people thrived in the adrenaline-fueled lifestyle if you avoided too many crutches. Weed and alcohol had long been part of the Wall Street scene, but the surge of cocaine usage in the 1980s was different and it ruined lives. The financial and personal rewards of working on Wall Street were diverse and many, but it came at a cost. I was lucky the era was ending because the constant travel, stress and pressure, drugs and alcohol, and too many late nights were taking a physical and mental toll on me too.</p>

<p>By the mid-1990s Wall Street life was settling down and regulatory changes were spurring new innovation. There were new alternatives to traditional exchanges like crossing and matching systems and investment bank “dark pools" that internalized orders. Most provided better prices, greater anonymity, and more transparent liquidity which with algorithms led to better execution prices on large trades like those of big institutional investors and funds.</p>

<p>High-frequency and algorithmic trading expanded from stocks into bonds, derivatives, commodities, and foreign exchange. Trades were now executed by “smart algorithms comparing fast, liquid electronic markets competing for order flow to get “best execution.” It was an IT speed race for high frequency arbitrage traders and market makers where milliseconds of speed difference and data insights meant low risk trading profits.</p>

<p>There were highly specialized hardware, software, data, network, and services vendors who sold financial institutions the means to compete and win. Everybody profited, some more than others. Digital transformation and algorithmic trading meant tighter spreads, better trade executions, and improved risk management and investor reporting. Both institutional and retail investors benefitted from better execution prices, and brokerage commissions became a thing of the past. Liquid, transparent, and efficient markets benefit everybody in good times and bad.</p>

<p>The stately marble environs of the NYSE or the amphitheater “trading pits" of the Chicago commodity and options exchanges had become expensive liabilities. Big trading floors were good TV sets for shows like CNBC’s Squawk on the Street where I did interviews, but nothing significant happened on exchange trading floors any longer after trading and market making was automated.</p>

<p>The cost of maintaining trading floors and legacy manual processes diverted investment from innovation and growth, and new alternative exchanges took more and more market share from traditional exchanges. The innovators expanded into new geographies, traded more asset classes electronically for longer hours, and prospered. Legacy exchanges that didn’t adapt either faded into oblivion or were acquired by the winners.</p>

<p>My former client NYSE was ultimately acquired by one of my new startup clients that our project team brought into existence, the Intercontinental Exchange (ICE). Against my advice NYSE ignored competitive threats for too long, were too slow transforming their IT infrastructure, and never executed a serious growth strategy. They stayed a private members-only club for too long while too many of the members had become dinosaurs. Public exchanges and especially European exchanges were using investment capital and the markets to fund aggressive expansion plans, forge global alliances, and make acquisitions.</p>

<p>As the '90s came to a close I had a front row seat to the separation of Andersen Consulting (AC) from Arthur Andersen (AA) and the global re-branding as Accenture preceding the blockbuster IPO. I’ll share the inside story of how we won the right to separate from AA and some previously untold stories of intrigue and political maneuvering along the way. Billions of dollars were at stake, and the story of how we executed a separation, global re-branding, and IPO in little more than a year will be on business school curriculums for many years.</p>

<p>It was one of the fastest, most complex, and highest value global business transformations ever undertaken, and the IPO was only 2 months before the 9/11 terrorist attacks. You’ll hear about the Andersen Worldwide global partners meeting in Paris where our future was decided and internal strategies to prevail in the International Chamber of Commerce arbitration. I was the long-time global client partner for our lead investment banker Goldman Sachs, and I was on the roadshow marketing Accenture IPO shares to big institutional investors as the capital markets managing partner.</p>
 
<p>I was in New York City on 9/11 and survived through a highly improbable twist of fate that involved a scheduled and then postponed London trip and a stop at my office before going to a big market data conference at Windows on the World. I survived while over a hundred colleagues, clients, and friends at the conference and working in the towers that day didn’t. Windows on the World was on the 106th floor of One World Trade Center, and nobody escaped from up there, all victims of senseless medieval religious fanaticism.</p>

<p>In the weeks after 9/11 Accenture helped clients and the city of New York recover even as we dealt with our own personal and professional losses. The region’s telecommunications and network infrastructure was destroyed in lower Manhattan, and the global financial industry would break down without those communication links between New York and the rest of the world reestablished. Nothing was ever the same afterwards, from flying to going through building security to meet with clients. The events of 9/11 prompted me to leave New York and move to South Carolina in 2003, but I still flew to NY or somewhere else in the world every week for another 15 years.</p>

<p>After resigning as the Accenture capital markets global managing partner in December, 2007 I did independent consulting, held capital markets training seminars, and served on boards for a few years before joining KPMG and leading Intelligent Automation. It gave me a chance to explore my new ideas for using software process automation and AI to drive innovation and operational efficiency beyond the limitations of global outsourcing. But after going back to work I found business life and norms had changed, and not for the better.</p>

<p>The preference-free meritocracy of Andersen Consulting and Accenture had given way to institutionalized special preferences and diversity goals. Goals became de facto became mandates for quotas in hiring, promotions, and compensation. I didn’t like it nor did high performers who lost out to preferred identity group members with inferior qualifications and performance.</p>

<p>Business outcomes suffered, and too much of leadership was too isolated from employees to see the widespread dissatisfaction. Top leadership was ensconced in top floor offices believing the empty HR corporate platitudes to promote diversity often superseding merit, and it resulted in new hire skill levels declining and many high performers not in a preferred identity group resigning</p>

<p>Wall Street in the '80s and '90s was an amazing experience in what were already pretty wild times, but I survived and thrived in the pace and pressure. I was a life in the fast lane but also an unprecedented period of innovation, market disruption, and the digital transformation of trading, capital markets, and global professional services. Later in my career I led Intelligent Automation where we were already selling process automation and AI long before public awareness of AI grew after the launch of ChatGPT. Anyway, here’s my story…</p>\n"""
